# This workflow will install Python dependencies and lint with Python 3.9
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Pylint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
        python -m pip install .
    - name: Lint with pylint
      run: pylint -j 0 translatepy
      continue-on-error: true
